More from fixes (#11736 and #12347)
npm/npm pull request #12518
Opened 2016-04-29 01:09 UTC by sminnee

One of these @iarna has already mentioned in comments in #12347.

These fixes both related to improving `npm shrinkwrap` reliability by getting more a consistent definition of `_from` values.

It still needs tests, which I'll try and get to over the next few days, but I wanted to expose my work-to-date.

2016-04-29 01:40 UTC, sminnee commented
Note that #11373 / #11493 is a related issue still not resolved by this.

2016-04-29 07:50 UTC, iarna commented on lib/cache/add-remote-git.js
> -              log.verbose('addRemoteGit', 'data._from:', resolvedURL, '(save-exact)')
I think even with your patch we need this behavior if `--save-exact` was used, as it saves with a commit id.

2016-05-09 18:49 UTC, iarna commented
Status note: This is waiting on an update that restores `--save-exact` behavior.

2016-06-20 15:03 UTC, xdissent commented
Anything else I can do to help with this one?

2017-07-18 05:27 UTC, zkat requested changes
Going to make a note also that this code literally does not exist anymore.

I'm not sure off the top of my head what the corresponding patch would be, though, and whether pacote would need to be patched -- pacote shouldn't have this sort of awareness about saving, imo.

2017-07-24 20:20 UTC, iarna commented
As the code this PR is patching is no longer in use (and indeed, I don't believe this is still an issue) I'm going to close this.

The original issue here, IIRC, is that subsequent installs from a shrinkwrap would end up with a `_from` pointing at the tarball URL and then that would go into the `from` field in future shrinkwraps, causing churn there.

Values for the shrinkwraps are no longer produced so naively, but more importantly, the `from` field is no longer included in shrinkwraps.

2017-07-24 20:20 UTC, closed without merging