Move when rename fails (fix EXDEV docker issues)
npm/npm pull request #13901
Opened 2016-09-08 10:19 UTC by chadnickbok

Currently, the npm 'rename' function is a thin wrapper around the `rename(2)` syscall. However, rename isn't guaranteed to be implemented by all filesystems, and can cause issues when running inside docker containers.

This patch changes the behavior of the 'rename' function to behave more like the traditional unix `move` command, falling back to recursively copying and deleting files if renaming them isn't possible.

I based my work on https://github.com/npm/npm/pull/13257 and I've tried to take into account the feedback on this PR:

 - Use a recursive strategy, trying to make use of 'rename' for as much of the work as possible (making it slower across-devices, but faster on AUFS for Docker).
 - Preserve most important file attributes when copying.
 - Testing - I don't think there are any valuable test cases that can be written for this functionality, as the only way to actually test it would be to setup a copy across filesystems, which is very system-dependent.

2016-09-08 23:46 UTC, legodude17 commented on lib/utils/rename.js
> +}
Any reason this file is sync? It should be async to conform to the rest of npm.

2016-09-08 23:47 UTC, legodude17 commented on lib/utils/rename.js
> +}
As well as this one.

2016-09-08 23:47 UTC, legodude17 commented on lib/utils/rename.js
> +}
Shouldn't this take a call back?

2016-09-08 23:47 UTC, legodude17 commented on lib/utils/rename.js
> +}
This should be sync.

2016-09-08 23:48 UTC, legodude17 commented on lib/utils/rename.js
> +}
And this.

2016-09-08 23:48 UTC, legodude17 commented on lib/utils/rename.js
>  }
And this.

2016-09-08 23:51 UTC, legodude17 commented
A bunch of line comments, mostly on the use of sync. This seems like a really good idea.

2016-09-09 18:17 UTC, chadnickbok commented on lib/utils/rename.js
> +}
Yes, looks like I didn't read the documentation closely enough!

2016-09-09 18:20 UTC, chadnickbok commented
Thanks for the comments!

Answer to all of them right now is - because the original `rename` was an atomic call, I can't drop-in replace it with an async operation. Basically right now anywhere that uses `rename` should expect it to be async, but it isn't. This patch fixes the behavior of `rename` to actually work on filesystems that don't support the `rename(2)` syscall, but it doesn't address all the places that would need to change to support an async call.

My proposal is to first fix the behavior of rename to be _correct_; then we can review and address making it async.

2016-09-09 18:47 UTC, chadnickbok commented
Great comments, this should absolutely be async. I'll move over to async operations for what I can

2016-09-10 00:33 UTC, legodude17 commented on lib/utils/rename.js
> +var rimraf = require('rimraf')
Shouldn't you use `lib/utils/gentlyRm.js` instead?

2016-09-10 02:32 UTC, chadnickbok commented on lib/utils/rename.js
> +var rimraf = require('rimraf')
Yes, great suggestion. I probably should have familiarized myself with the rest of the guild directory before jumping in with a rewrite!

What do you think of the rest of this code?

2016-09-10 16:13 UTC, legodude17 commented on lib/utils/rename.js
>    var saved = new SaveStack(rename)
What does this do?

2016-09-10 16:54 UTC, chadnickbok commented on lib/utils/rename.js
>    var saved = new SaveStack(rename)
Its from the original `rename` - I believe it makes sure that the stack trace includes the call to this function (although tbh I'm not entirely sure)

2016-09-10 17:43 UTC, chadnickbok commented on lib/utils/rename.js
> +var rimraf = require('rimraf')
Unfortunately not.

gentlyRm takes paths relative to the npm prefix: https://github.com/npm/npm/blob/master/lib/utils/gently-rm.js#L54

Whereas `rename` takes paths relative to `process.pwd` (this is implicit in the call to `rename(2)`)

Changing over to using `gentlyRm` breaks tests; I'd need to refactor all callers of `rename` to make this change, and its not something I think should be in scope for this PR

2016-09-10 17:52 UTC, chadnickbok commented on lib/utils/rename.js
> +var rimraf = require('rimraf')
Great suggestion! I didn't realize what gentlyRm was doing, but it seems reasonable :)

2016-09-12 14:34 UTC, legodude17 commented on lib/utils/rename.js
>    var saved = new SaveStack(rename)
Yeah I saw that now.

2016-09-14 02:51 UTC, rachael commented
I like this PR as a replacement for my PR #13257. @chadnickbok is more knowledgeable than me about the necessities of interacting with filesystems and the addition of async makes it much better than my band-aid fix.

@zkat if my PR was good to merge without any additional tests would that mean this one is good to go?

2016-10-03 23:54 UTC, iarna commented on lib/utils/rename.js
>    var saved = new SaveStack(rename)
Yup, without this errors in rename have no stacktrace at all, because they lead back to the callback being called from Node.js internals.

2016-10-04 00:43 UTC, iarna requested changes
Mechanically I'm happy with what this code is doing.

I'm not comfortable with the way it's recursing. Limiting that recursion with the `setImmediate` loop is a symptom of that, but not in and of itself the problem.

I would prefer that this use a work queue and handle one file at a time. This theoretically is slower, but in practice this shouldn't be happening too often and copying is already plenty slow.

That... might be a little vague? Here's some psuedocode of how I'd approach it: (Uhm, sorry in advance if I've swung way too far over into "too specific" here. =D)

``` js
function safeRename (from, to, cb):
  workQueue = [[tryRename, from, to]]
  _safeRename()
  function _safeRename:
    if (!workQueue.length)
    [action, from, to] = workQueue.shift()
    action(from, to, _safeRename)
  function tryRename (from, to, cb):
    fs.rename(from, to, function (err) {
      if (err):
        if (err is EXDEV or other docker error):
          workQueue.push([copy, from, to])
        else:
          return cb(err)
      cb()
    })
  function copy (from, to, cb):
    fs.stat(from, to, function (err, stat) {
      if (err) return cb(err)
      if (isFile) workQueue.push([copyFile, from, to])
      else if (isSymlink) workQueue.push([copySymlink, from to])
      else if (isDir) workQueue.push([copyDir, from, to])
      else return cb(someError)
      cb()
    })
  function copyDir(from, to, cb):
    fs.readdir(from, function (err, items) {
      if (err) return cb(err)
      items.forEach(function (item) {
        workQueue.push([tryRename, path.join(from, item), path.join(to, item)])
      })
      cb()
    })

  copyFile & copySymlink would work as they do now, except with callbacks for when they're done.
```

2016-10-04 00:43 UTC, iarna commented on lib/utils/rename.js
> +    if (running >= limit) {
So... if it hits its concurrency limit it... hard loops using setImmediate until some of the outstanding `lstat`s complete?

I'm not comfortable with this implementation. This should either be using a tool to limit concurrency (like [call-limit](https://www.npmjs.com/package/call-limit)) or doing so structurally.

I'll come back to that second bit below…

2016-10-04 00:43 UTC, iarna commented on lib/utils/rename.js
> +    writeStream.on('open', function () {
Why wait for `open` to start piping?

2016-10-04 00:43 UTC, iarna commented on lib/utils/rename.js
> +    var target = source.replace(currentPath, targetPath)
Using text replacement here feels brittle to me…

2016-10-04 00:43 UTC, iarna commented on lib/utils/rename.js
> +  function getStats (source) {
This function name seems a bit too centered on the mechanics and not the logic of what it's doing. Which is… looking at what kind of thing the path is and selecting the appropriate path for renameOrCopy?

2016-10-04 00:43 UTC, iarna commented on lib/utils/rename.js
> +      items.forEach(function (item) {
So... this is where you end up having to have your unusual concurrency controls.

I would use something like [`asyncMap`](https://www.npmjs.com/package/slide#asyncmap) or [`chain`](https://www.npmjs.com/package/slide#chain) to iterate over the directory entries.

That doesn't automatically save you from the giant async-bomb of recursion going on here but I'll talk more about that in my general review comment.

2016-10-04 00:52 UTC, iarna commented
I've discussed this further with @othiym23 & @zkat and we agree that this will need tests. I'd like to see two sorts of things:

1. A test that shows that exercises the copying code being introduced here. To write this you'd need to use `requireInject` to replace `graceful-fs`'s `rename` method with something that failed with EXDEV for certain directories. I'd like to see this test exercise copyFile, copyDir & copySymlink.

2. A functional test that, without this patch, fails consistently in a docker environment would be super useful. Bonus points for including a Dockerfile that runs said test. I expect this to be doable in light of the Dockerfile in #9863. The only changeup from what it's doing is that the test needs to not install modules off the network.

2016-10-04 03:57 UTC, chadnickbok commented
Okay, great comments I'll try to implement the suggestions over the next day or two.

One thing I do want to mention is that I based these changes on the widely-deploy `ncp` utility - https://github.com/AvianFlu/ncp/blob/master/lib/ncp.js
That's where the non-standard concurrency controls come in.

Before I go any further, I want to be _really_ clear that the proposed work-queue based approach will be slow in the case where all files need to be copied, and that we're _explicitly_ signing up for that slowness. In the case of docker and aufs, this shouldn't actually be terribly slow, since we'll be making use of `rename` for most of that (and making the kernel do the hard work), but for filesystems that require a full copy its going to be significantly slower.

2016-10-04 23:23 UTC, iarna commented
It is, but I'm also not aware of any scenarios where this would trigger besides Docker and aufs. At least, thus far, you all are the only one's making noise about it.

And if need be we can rejigger the work queue to handle _n_ items in it concurrently, when the time comes.

2016-10-04 23:24 UTC, iarna commented
Incidentally: I traced the ncp code back to a commit from 2011(!) which really does a lot to explain why it's so weird. =D

2016-10-05 14:39 UTC, legodude17 commented on lib/utils/rename.js
> +    writeStream.on('open', function () {
Yeah, shouldn't pipe automatically wait for both streams to be ready?

2016-11-28 15:45 UTC, justincormack commented
It will be difficult to do a functional test that fails in a Docker environment as that Docker environment needs to be using `aufs` or `overlay` which not all are.

You can perhaps make a test in an environment with some bind mounted files, not sure.

2016-12-12 22:42 UTC, iarna commented
@justincormack Personally, I'd make a functional test that injects an `fs` replacement that emits `EXDEV` when trying to rename from `.staging` to an ordinary `node_modules` location.

2017-03-01 01:30 UTC, iarna commented
This is superseded by #15901.

2017-03-01 01:30 UTC, closed without merging