shrinkwrap: fix optional deps check
npm/npm pull request #14117
Opened 2016-09-29 01:15 UTC by watilde

Fixes https://github.com/npm/npm/issues/14042. From the last release, `npm-shrinkwrap.json` has been updated to tell us the deps is optional or not, but instal-check in `install/action.js` still has been checking the deps could be installable or not even the deps has `optional: true`.

I've updated `inflate-shrinkwrap.js` to pass the property of the optional to `action.js` and  `isInstallable ` should be skipped if the deps is optional. I will add a test and write more detail into the commit message later. Thanks!

2016-09-29 01:56 UTC, iarna requested changes
This is going to need a test, because my reading of the code is that this makes the scenario outlined in the issue worse, not better.

I _believe_ the scenario in the issue is related to rollbacks of transitive deps of optional deps causing an "exit with error" condition when they shouldn't.

2016-09-29 01:56 UTC, iarna commented on lib/install/actions.js
> +    if (pkg.knownInstallable || pkg.package._optional) {
My reading of this code:

If the shrinkwrap flagged this package as optional then don't bother checking to see if it meets archictecture or OS requirements?

Isn't that the opposite of what we want?

2016-09-30 07:50 UTC, watilde commented on lib/install/actions.js
> +    if (pkg.knownInstallable || pkg.package._optional) {
True. It should be handled through the errorMessage like the general `optionalDependencies` way of `install.js`. I will update them again!

2016-10-03 00:02 UTC, watilde commented on lib/install/actions.js
> +    if (pkg.knownInstallable || pkg.package._optional) {
Ok! I've updated the code and added a test for the case.  Here is the minimum case to reproduce the original issue: https://github.com/watilde/npm-issue-14042

2016-10-03 21:58 UTC, iarna commented
This looks much better! I'm still concerned that apparently our optionalDependency checker is failing under some circumstances (that you've isolated). I'd _prefer_ not to have to fall back on assuming the shrinkwrap is correct regarding the optional status of packages.

So this is my plan:

1. I plan on taking this patch, because as long as we have optional in the shrinkwrap I think we should believe it.
2. I'm going to pull out your reproducer and see if I can't figure out what the root cause of the failure is.

I'd like to get #2 done before I land #1 as having #1 in place will make it harder to reproduce.

2016-10-04 22:23 UTC, watilde commented
Your plan looks good to me! Let me know if you need more help :)
I guess the optional status of the package should be transferred to our optionalDependency checker as just one optional dependency instead of the optional property eventually.

2016-10-20 10:41 UTC, iarna commented
This has been merged into `release-next`

2016-10-20 10:41 UTC, closed without merging