The npm shrinkwrap file needed to have is full path specified.
npm/npm pull request #14143
Opened 2016-09-30 18:29 UTC by lholmquist

fixes issue #14009.  

The problem was that the `git add` of the npm-shrinkwrap.json was failing, since it was looking for it in the wrong directory.  Adding in the actual path to the shrinkwrap file similar to https://github.com/npm/npm/blob/master/lib/version.js#L145 fixes the issue

2016-10-03 21:51 UTC, iarna requested changes
Thank you! This is very similar to the bug we fixed in the version lifecycle a little bit ago. Unfortunately it seems our test suite doesn't often test running lifecycles outside the project root.

While getting more general tests across our various lifecycles is outside of scope, I'd like to see a test for this particular bug as part of this PR.

2016-10-04 13:27 UTC, lholmquist commented
@iarna sure thing

2016-10-04 19:23 UTC, lholmquist commented
@iarna added a test for this.  it was basically just a c/p of another test.  :)  I also squashed the commits into 1, if they need to be 2, let me know

2016-10-04 20:21 UTC, lholmquist commented
@iarna not really sure why that appveyor check is failing though

2016-10-04 23:26 UTC, iarna commented
Yeah, the AppVeyor definitely isn't your fault =) 

And 1 commit is perfect, thanks!

2016-10-06 22:06 UTC, iarna commented
This has been merged into the `release-next` branch and will be in the next release later today.

2016-10-06 22:06 UTC, closed without merging