Improve output of `npm ping`
npm/npm pull request #14461
Opened 2016-10-28 22:41 UTC by legodude17

This makes it much clearer when `npm ping` succeeds or fails.

2016-10-30 16:28 UTC, watilde commented on test/tap/ping.js
> +      t.same(stdout, 'Ping succeeded: ' + JSON.stringify(pingResponse))
This message should be `t.same(stdout, 'Ping success: ' + JSON.stringify(pingResponse))`

2016-10-30 22:19 UTC, legodude17 commented on test/tap/ping.js
> +      t.same(stdout, 'Ping succeeded: ' + JSON.stringify(pingResponse))
Ok all done

2016-11-03 22:55 UTC, iarna requested changes
It would be helpful if you could squash your commits and use our commit message style. (That is: `<thing changed>: <less than 60 char desc>`, so in this case `ping: something something`)

I'd like to see `doc/cli/npm-ping.md` describe its output. It currently doesn't, which was an oversight from when we originally added this feature.

As a rule, we generally consider what's printed to STDOUT to be a part of our contract, and thus changing that constituting a breaking change. In this case though, particularly seeing as we hadn't documented it previously, I think I'm ok with changing the output.

2016-11-03 23:54 UTC, legodude17 commented
I am sorry, but I can't figure out how to rebase. I am not sure what is going on. I ran `git rebase -i HEAD~7`, but then it took me to `vi` and I couldn't get out. ☹️

2016-11-04 00:20 UTC, legodude17 commented
What? I thought I rebased and squashed, but now it says I added two commits. I am so confused. What should I do now @iarna?

2016-11-04 14:30 UTC, KenanY commented
@legodude17 Maybe try (off the top of my head):

1. Set your `git` editor to your preferred one: `git config --global core.editor "vim"` (replace `"vim"`)
2. Do `git rebase -i HEAD~9`. Your editor should open a file that looks something like this:

```
pick 7ae4be0
pick 2790146
pick 47b23e9
pick 437a6f6
pick 48ebcfe
pick 20639b1
pick c49565d
pick 21c66f7
pick ca63015
```

3\. For every line but the first, change "pick" to "squash", like so:

```
pick 7ae4be0
squash 2790146
squash 47b23e9
squash 437a6f6
squash 48ebcfe
squash 20639b1
squash c49565d
squash 21c66f7
squash ca63015
```

4\. Save this file. You can then do `git commit --amend` if you would like to change the commit message.

5\. Verify it worked with `git log`
6\. Force-push your changes: `git push -f origin patch-2`

2016-12-14 02:00 UTC, legodude17 commented
Ok @iarna. Did both of those things. Re review?

2016-12-17 23:44 UTC, iarna approved these changes
Looking good, thank you!

2017-08-12 23:42 UTC, iarna commented
This has been merged into bde151902 in release-next and will be in the next release of npm.

2017-08-12 23:42 UTC, closed without merging