shrinkwrap: fix scoped dependency resolution from from
npm/npm pull request #14462
Opened 2016-10-29 01:46 UTC by zkat

346bba1 broke the way shrinkwrap `from` got parsed.
Because of the way the `lookup` function here is treating
it as a version, the specified was being resolved as a
local package in the current directory.

This brings back the URL check to protect against this case,
which was only happening for scoped packages

2016-11-03 22:25 UTC, othiym23 requested changes
Some semi-nitpicky changes, but the change & test are pretty simple. Lemme know when to look again!

2016-11-03 22:25 UTC, othiym23 commented on test/tap/shrinkwrap-no-resolved.js
> +  // 'foo': Dir({
baleet plz

2016-11-03 22:25 UTC, othiym23 commented on test/tap/shrinkwrap-no-resolved.js
> +// NOTE: This test will only remain relavent until npm@5 when
s/relavent/relevent/

2016-11-03 22:25 UTC, othiym23 commented on test/tap/shrinkwrap-no-resolved.js
> +// npm-shrinkwrap.json will override EVERYTHING in you package.json.
s/you/your/

2016-11-03 22:38 UTC, othiym23 commented
LGTM. Merge at will. :sheep::rocket::fire:

2016-11-03 22:38 UTC, othiym23 approved these changes

2016-11-03 22:40 UTC, merged

2016-11-04 02:16 UTC, iarna commented on test/tap/shrinkwrap-no-resolved.js
> +  common.npm(['install'], {registry: 'nope', cwd: testdir}, function (err, code, out, stderr) {
The options object is passed to `child_process.spawn`. This should be:

`common.npm(['install', '--registry=nope'],…`

2016-11-04 02:17 UTC, iarna commented on test/tap/shrinkwrap-no-resolved.js
> +    t.is(err, null, 'No fatal errors running npm')
That's not what `err` means. `err` will ONLY be set if there's an OS error when forking. Check `code` for `npm`'s error status.

I strongly the use of `scripts/maketest` to generate the boilerplate, as it does all this stuff for you.

2016-11-04 02:19 UTC, iarna commented on test/tap/shrinkwrap-no-resolved.js
> +        from: 'foo'
So if you take out the `@blarg/foo` you'll see that `npm` tries to install this from the network even though it's a local file. Similarly if you have a `github` shortcut, eg `foo/bar`, here, it'll also use the network inappropriately.

2016-11-04 02:20 UTC, iarna commented on test/tap/shrinkwrap-no-resolved.js
> +        from: 'foo'
I think testing this will require splitting this out into two separate test cases to show that they both fail in the way we expect.

2016-11-04 02:21 UTC, iarna commented on lib/install/realize-shrinkwrap-specifier.js
> +  } else if (sw.from && url.parse(sw.from).protocol) {
Maybe pass this to `npa` and if it's not a version or range then do this code path?

2016-11-04 02:25 UTC, iarna commented on lib/install/realize-shrinkwrap-specifier.js
> +  } else if (sw.from && url.parse(sw.from).protocol) {
On second thought, that's basically what the code in here does already. I think we need to dig further into the root cause here, which I believe would be that `isRegistrySpecifier` is doing the wrong thing somehow? Which implies that in turn `realizePackageSpecifier` is doing the wrong thing?