Clarify the behavior of the `files` array
npm/npm pull request #15234
Opened 2016-12-15 21:09 UTC by jbcpollak

The `files` documentation is a bit confusing (and actually incorrect with respect to current `files` vs `.npmignore` behavior, so I hope this clarifies it.

2017-02-23 11:46 UTC, coconutperm approved these changes

2017-02-23 17:14 UTC, legodude17 requested changes
Nice PR!

(Note that I am not a developer of `npm`, just a community member)

2017-02-23 17:14 UTC, legodude17 commented on doc/files/package.json.md
> +inside that folder. (Unless they would be ignored by another rule in this section.)
Move this paragraph down.

2017-02-23 17:14 UTC, legodude17 commented on doc/files/package.json.md
> +`.npmignore` or `.gitignore`.
Put the description of files down here.

2017-02-24 00:21 UTC, jbcpollak commented on doc/files/package.json.md
> +`.npmignore` or `.gitignore`.
@legodude17 I am ok with the change you suggest, but was trying to minimize the documentation change under the theory that would be more acceptable to the core team. I'm happy to update if that is preferred.

2017-02-24 22:29 UTC, legodude17 commented on doc/files/package.json.md
> +`.npmignore` or `.gitignore`.
I would say it makes more sense to merge the `Files included with the "package.json#files" filed....` and the `The "files" field....` paragraphs.

2017-08-13 00:07 UTC, iarna commented
This is definitely an improvement (for future reference, you _can_ override `files` with a `.gitignore` or `.npmignore` in a _subdirectory_, but not at the top level.)

I've merged  this as a0fdd1571. Thank you for your patience.

2017-08-13 00:07 UTC, closed without merging