Respect PREFIX and DESTDIR in combination
npm/npm pull request #15519
Opened 2017-01-18 12:15 UTC by rotty

Convention dictates that these two variables should be usable in
combination. Fixes #15517.

2017-01-23 22:46 UTC, iarna requested changes
Thanks for finding this! This needs one very minor tweak and a test.

2017-01-23 22:46 UTC, iarna commented on lib/config/defaults.js
> +  if (process.platform !== 'win32' && process.env.DESTDIR) {
This should use `lib/utils/is-windows.js`

2017-01-28 11:40 UTC, dangonzo commented on lib/config/defaults.js
> +  if (process.platform !== 'win32' && process.env.DESTDIR) {
use ruby

2017-08-17 20:18 UTC, iarna commented
Looking at this again 7 months later, I see that the win32 test is done directly throughout that file, so I'm fine with not using `is-windows.js` but it would still need a test to land.

As it's been so long with no activity I'm going to close this, but we would be happy to take a new PR in future that includes a test for this functionality.

2017-08-17 20:18 UTC, closed without merging