feat: add "npm org" command
npm/npm pull request #16452
Opened 2017-04-27 00:29 UTC by chrisdickinson

This adds support for adding, removing, and listing org memberships from the command line!

```
$ npm org add npmcorp chrisdickinson admin
$ npm org set npmcorp chrisdickinson developer
$ npm org rm npmcorp chrisdickinson
$ npm org ls npmcorp
```

2017-04-27 00:33 UTC, zkat commented
@chrisdickinson Could you add some tests? https://github.com/npm/npm/blob/latest/test/tap/team.js is the corresponding test for team.

2017-04-27 00:39 UTC, zkat approved these changes
LGTM 👍

2017-04-27 01:02 UTC, iarna requested changes
I'm of the opinion that cli commands should never emit JSON unless explicitly asked to with `--json` and that we should come up with some human readable output format for these commands.

There also need to be docs for these new commands.

2017-05-01 06:47 UTC, watilde commented on lib/org.js
> +    try {
Probably, we can get rid of this `try-catch` like the other implementations.

2017-05-01 07:00 UTC, watilde commented on node_modules/npm-registry-client/index.js
> +  client.org = require('./lib/org')
Somehow we're missing this module file. Let's run:
> $ scripts/dep-update npm-registry-client 8.2.0

2017-05-27 20:59 UTC, zkat commented on lib/config/cmd-list.js
> +  'ogr': 'org',
👹

2017-06-01 14:17 UTC, watilde commented on lib/config/cmd-list.js
> +  'ogr': 'org',
might be fine as an affordance?

2018-07-10 23:03 UTC, zkat commented
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

2018-07-10 23:03 UTC, closed without merging

2018-07-10 23:04 UTC, zkat commented
Additionally, chris, a new version of this might want to follow the implementation of `npm hook`, and use `npm-registry-fetch` plus a `libnpmorg` or something.