Add support for long option to view output
npm/npm pull request #16602
Opened 2017-05-11 17:46 UTC by andytompkins

This PR adds support for the "--long" option for view output.
Issue was filed here: https://github.com/npm/npm/issues/16590
Without the option the behavior is exactly the same as before. With the long option the array output will not be truncated (and in my use case, all versions will be shown).

2017-05-11 17:48 UTC, legodude17 commented
I think that by default is should just JSON stringify it and print it.

2017-06-30 08:46 UTC, iarna commented
As a rule, changes need tests and docs. I'm prepared to forgo tests for this, but adding a mention to the `view` docs would be nice.

2017-06-30 08:46 UTC, iarna requested changes
As a rule, changes need tests and docs. I'm prepared to forgo tests for this, but adding a mention to the `view` docs would be nice.

2017-08-17 18:31 UTC, iarna commented
We're closing this pull request as it has gone sixty days without activity after we requested changes.  In our experience pull requests that go this long are unlikely to land.  If you do write docs for this, please don't hesitate to open a new pull request.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).

2017-08-17 18:31 UTC, closed without merging