Added support for always-auth and _auth. Both for root and scopes
npm/npm pull request #16879
Opened 2017-06-01 17:16 UTC by jozemlakar

I had added the loading of auth config when always-auth and _auth are set.
I had added the sending of authorization header in the mentioned case. 
I have tested this against artifactory, when set globally. Someone else might want to test it against other registries or when scopes are used.

2017-06-01 17:31 UTC, snirad commented on lib/config/pacote.js
> +      /(.*):(_authToken|username|_password|password|email|always-auth|_auth)$/
this regex assume we use 
//registry.npmjs... type of syantax.

could you please change it like so ?

/((.*):)?(_authToken|username|_password|password|email|always-auth|_auth)$/

2017-06-01 17:47 UTC, snirad reviewed
- sorry for the confusion , now i see that it works even without adding this regex, but maybe it is still needed, im not sure.

2017-06-02 00:15 UTC, zkat requested changes
So far so good! A few things to improve first 👍

2017-06-02 00:15 UTC, zkat commented on node_modules/pacote/lib/fetchers/registry/fetch.js
>    }
These changes should be files as a separate PR against `pacote`.

2017-06-02 00:15 UTC, zkat commented on lib/config/pacote.js
> +  if (!!npm.config.get('always-auth')) {
I'd rather not coerce to boolean here. Let `if` do its usual work?

2017-06-02 00:15 UTC, zkat commented on lib/config/pacote.js
> +
Please make sure the code passes `standard` linting.

2017-06-02 00:15 UTC, zkat commented on lib/config/pacote.js
> +    if (!!npm.config.get('_auth')) {
This can't just be for `_auth`. All of the other auth parameters listed below should be made available as toplevel settings.

2017-06-02 11:43 UTC, snirad commented on lib/config/pacote.js
> +      /(.*):(_authToken|username|_password|password|email|always-auth|_auth)$/
how about adding this line just below, and making authMatch ; let instead of const.
that should hold for all cases, and you can remove that if condition you added just for _auth

`
  npm.config.keys.forEach(function (k) {
    let authMatch = (k[0] === '/' && k.match(/(.*):(_authToken|username|_password|password|email|always-auth|_auth)$/))
   if(!authMatch && /(_authToken|username|_password|password|email|always-auth|_auth)$/.test(k)){
        authMatch =[,registryKey(opts.registry), k]
}
    if (authMatch) {
      const nerfDart = authMatch[1]
      const key = authMatch[2]
      const val = npm.config.get(k)
.........................

`

- also we will need to import registryKey functoin as wel

`function registryKey (registry) {
  const parsed = url.parse(registry)
  const formatted = url.format({
    host: parsed.host,
    pathname: parsed.pathname,
    slashes: parsed.slashes
  })
  return url.resolve(formatted, '.')
}`

what do you think,
@zkat , @jozemlakar

2017-06-02 14:04 UTC, jozemlakar commented on lib/config/pacote.js
> +      /(.*):(_authToken|username|_password|password|email|always-auth|_auth)$/
sounds good. I am currently working on tests on a change in https://github.com/zkat/pacote and will then do config. Whatever the final solution, it should be the same for scoped and global settings, so my first one is no good.

2017-06-02 17:31 UTC, jozemlakar commented on node_modules/pacote/lib/fetchers/registry/fetch.js
>    }
Added https://github.com/zkat/pacote/pull/96

2017-06-05 06:05 UTC, jozemlakar commented on lib/config/pacote.js
> +      /(.*):(_authToken|username|_password|password|email|always-auth|_auth)$/
So, looked at this issue and here is where I stand:
- PR created for pacote. I think that should clear. Once that lands we can update the dependency in npm
- There is only one general test for config/pacote in npm, so the first thing I need to do is create a test for config parsing
- Fix config parsing so we get all options (including _auth) both on global and scoped.

2017-06-05 12:30 UTC, jozemlakar commented
I think this is now complete. It adds support for all auth options, uses options in the same manner when scoped and global.

2017-06-07 23:41 UTC, zkat approved these changes

2017-06-07 23:41 UTC, zkat commented
Awesome work! Yay tests! I'll merge this once the test suite passes. Thanks a bunch 🎉

2017-06-08 00:24 UTC, zkat commented
@jozemlakar the tests seem to be failing right now :< https://travis-ci.org/npm/npm/builds/240593681?utm_source=github_status&utm_medium=notification

2017-06-08 04:08 UTC, jozemlakar commented
@zkat seems that registry configured in test is no longer used but rather goes to default public registry. Will look into it.

2017-06-08 09:45 UTC, jozemlakar commented
@zkat Build was broken with https://github.com/npm/npm/pull/17076
when merged without running tests first https://github.com/npm/npm/pull/16879/commits/c8528297ada8a542385efbefa6ca0d776bbb6342

Without that change the config is
```
{ type: 'remote',
  registry: undefined,
  where: undefined,
  raw: '@scoped/underscore@http://localhost:1337/scoped-underscore/-/scoped-underscore-1.3.1.tgz',
  name: '@scoped/underscore',
  escapedName: '@scoped%2funderscore',
  scope: '@scoped',
  rawSpec: 'http://localhost:1337/scoped-underscore/-/scoped-underscore-1.3.1.tgz',
  saveSpec: 'http://localhost:1337/scoped-underscore/-/scoped-underscore-1.3.1.tgz',
  fetchSpec: 'http://localhost:1337/scoped-underscore/-/scoped-underscore-1.3.1.tgz',
  gitRange: undefined,
  gitCommittish: undefined,
  hosted: undefined }
```

after change the config is
```
{ type: 'version',
  registry: true,
  where: undefined,
  raw: '@scoped/underscore@1.3.1',
  name: '@scoped/underscore',
  escapedName: '@scoped%2funderscore',
  scope: '@scoped',
  rawSpec: '1.3.1',
  saveSpec: null,
  fetchSpec: '1.3.1',
  gitRange: undefined,
  gitCommittish: undefined,
  hosted: undefined }
```

As a result, npm is sending the request to public npm registry instead of the mock.

I have no idea why this was changed or how this passed existing tests. Please have a look at it.

2017-06-09 21:04 UTC, jozemlakar commented
@zkat if you need me to check something or try something out, let me know. My knowledge of shrinkwrap is next to zero, so I really can't handle the changes you made on my own.

2017-06-11 15:39 UTC, jozemlakar commented
@zkat in case I was not understood. Commit https://github.com/npm/npm/commit/c8528297ada8a542385efbefa6ca0d776bbb6342 breaks existing tests i.e. shrinkwrap-scoped-auth.js
When you fix that I can fix other tests I created based on that one.

2017-06-11 15:53 UTC, jozemlakar commented
@snirad you are absolutely correct! I remove the lines, thank you.

2017-06-15 11:17 UTC, jozemlakar commented
@kat this is now ready. Once i pulled all the changes from release-next and synced my tests with the ones you changed tests succeed.

2017-06-19 07:42 UTC, snirad commented
@zkat  hi kat :) 

any chance we get to see it on 5.0.4 ?

2017-06-29 02:27 UTC, zkat commented
This has been merged into `release-next` and is available in `npmc@5.0.4-canary.4`!

2017-06-29 02:27 UTC, closed without merging