Fix wrong symlink direction in link documentation
npm/npm pull request #16966
Opened 2017-06-04 16:14 UTC by rizip1

In npm-link documentation it is written that after running
```npm-link package-name``` symlink is created from global
folder to node_modules of the current project.

However the symlink is created from node_modules of the current
folder to the global folder, otherwise there would be no
way to achieve linked module. So I swapped the direction
in the documentation.

2017-06-27 01:57 UTC, iarna requested changes
I'm finding both versions of these docs confusing. (Actually I find the original less confusing, but I'm having trouble articulating _why_.)

Maybe it would be best to rewrite the entire paragraph to be clearer. I was looking at how `man ln` describes it…
```
ln TARGET LINK_NAME 

create a link to TARGET with the name LINK_NAME
```
We create a link to the globally-installed `package-name` with the name `node_modules/package-name`.

I guess it's just that lonely `node_modules/` that's mixing it up for me?

2017-07-04 10:43 UTC, rizip1 commented
Could you somehow describe what is confusing on PR version? I find it quite understandable.

2017-07-07 03:46 UTC, iarna commented
@rizip1 I guess because if I'm creating that link by hand the order is: `ln /global/dir/pkgname node_modules/pkgname` and your documentation puts that in the opposite order.

2018-07-10 23:02 UTC, zkat commented
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

2018-07-10 23:02 UTC, closed without merging