fix(git): git repos with prepare scripts always install with dev flag
npm/npm pull request #17060
Opened 2017-06-07 15:32 UTC by intellix

Closes #17059

2017-06-07 23:25 UTC, zkat requested changes
Thanks for finding this!

2017-06-07 23:25 UTC, zkat commented on lib/pack.js
> +        '--only=dev',
This will only install `devDependencies` and not `dependencies`. Did you want to use `--dev`?

2017-06-08 08:23 UTC, intellix commented on lib/pack.js
> +        '--only=dev',
I did originally have --dev but when I used it locally it told me that it's deprecated and that i should be using --only=dev so I assumed the name was misleading :)

2017-06-08 08:29 UTC, intellix commented
Addressed comments :)

2017-06-27 01:47 UTC, iarna commented on lib/pack.js
> +        '--dev',
I think there should be a `--prod` here as well to protect us against users who were doing an `--only=dev` install previously.

2017-06-27 04:14 UTC, intellix commented on lib/pack.js
> +        '--dev',
SGTM and solved :)

2017-06-29 02:42 UTC, zkat approved these changes

2017-06-29 02:45 UTC, merged