Add possibility to ls only linked packages
npm/npm pull request #17616
Opened 2017-07-05 09:01 UTC by richardsimko

This is a fix for #16126 (Even though it was automatically closed by the bot) which I finally got around to implementing. The idea is to give users the ability to list only packages which have been linked using `npm link`, to get an overview of those (Useful for teams with many internal modules).

Also see this [Stackoverflow question](https://stackoverflow.com/q/24933955/1091402) (Not mine) for proof that there is demand for this feature.

2017-07-05 21:35 UTC, zkat commented
Hey, we had to do a force-push to `release-next`. Would you kindly rebase your code onto the latest `release-next`? Cheers <3

2017-07-06 06:12 UTC, richardsimko commented
Done and done!

2017-07-06 20:52 UTC, zkat commented
@RichardLitt hi!

Ok so we talked about it, and we're ok with this patch, with two changes:

1. We don't need a new option! I think it's 💯 to just reuse the existing `--link` option and just add a detail about what it means to `npm ls`.

2. It would be nice to have a test for this. You can probably crib something from `test/tap/link.js`, or even, I think, add a single test _inside_ that file to make sure `ls` is reporting what it should, here. Either way is fine by me.

2017-07-06 20:53 UTC, zkat requested changes
Requested some changes. See above comment. Otherwise, the idea is ok and we'll totally take it!

2017-07-06 20:55 UTC, RichardLitt commented
@richardsimko what do you think? I think tests sound good, and using `npm ls` also works.

2017-07-06 21:00 UTC, zkat commented
ahahah I'm sorry, @RichardLitt. Defeated by the autocomplete. This was totally meant for @richardsimko 😂

2017-07-06 21:01 UTC, RichardLitt commented
All good. It's a good PR!

2017-07-07 06:03 UTC, richardsimko commented
Great! I did consider re-using `--link` but I couldn't quite figure out if it made sense but I absolutely agree, I'll change it. Thanks for the pointer on where to put the tests.

2017-07-07 06:34 UTC, richardsimko commented
Done and done! Did I put the docs in the right place?

2017-07-07 09:05 UTC, richardsimko commented
The broken build is not my fault 😢  It complains about some styling error in a file from 183d1058cde1c360aaaf988eb95aa08e8e82c648 it seems.

2017-07-11 08:50 UTC, richardsimko commented
@zkat Have you had a chance to look at my changes? :)

2017-07-12 07:21 UTC, zkat commented
Oh. Yeah, this lgtm. 👍

2017-07-12 07:21 UTC, zkat approved these changes

2017-07-12 07:23 UTC, merged