Fixed lockfiles not being added to the "npm version" commit
npm/npm pull request #17742
Opened 2017-07-12 11:29 UTC by markpeterfejes

Hey!

This small PR fixes #17707 by executing the `git add` commands sequentially instead of concurrently, which sometimes causes the aforementioned error.

I'm not really sure that this is the prettiest way to implement this, change suggestions are very welcome!

Thank you!

2017-07-12 22:22 UTC, zkat requested changes
needs a small mostly-stylistic change

2017-07-12 22:22 UTC, zkat commented on lib/version.js
> +  return new BB(function (resolve, reject) {
You don't need a promise constructor here. Just:

```
return addLocalFile('package.json', options, false).then(() => {
  if (localData.hasShrinkwrap) {
    return addLocalFile('npm-shrinkwrap.json', options, false)
  } else if (localData.hasPackageLock) {
    return addLocalFile('package-lock.json', options, false)
  }
})
```

2017-07-13 08:22 UTC, markpeterfejes commented on lib/version.js
> +  return new BB(function (resolve, reject) {
I'm doing this right now! Is there a possibility that this could be merged to the 5.3.0 relese today?

2017-07-13 08:33 UTC, zkat commented on lib/version.js
> +  return new BB(function (resolve, reject) {
probably! I'll take a look in the AM and see if this patch is ready to merge. 👍

2017-07-13 08:39 UTC, markpeterfejes commented on lib/version.js
> +  return new BB(function (resolve, reject) {
Thank you very much!

2017-07-13 20:00 UTC, markpeterfejes commented
Should be ready for release :)

2017-07-13 21:08 UTC, zkat approved these changes
changes look good, everything seems to work. gj, and thanks for the contrib! 🎉

2017-07-13 21:09 UTC, merged