Return non zero exit code when no tests defined.
npm/npm pull request #18707
Opened 2017-10-04 12:43 UTC by DanBUK

When running npm test, if it's not defined in package.json currently npm returns an exit code of 0, yet displays an error.

This PR changes that to return an exit code of 1 if it's not defined.

2017-11-21 01:38 UTC, iarna commented
This would also bring things into alignment with `npm init`. This seems reasonable to me.

2017-11-21 01:39 UTC, iarna commented
TBH, I didn't even know we had this special case. I wish we didn't. =p

2017-11-21 01:40 UTC, iarna commented
This was merged to `release-next` as e71386d98 and will be in (as the branch name implies) our next release. Thanks!

2017-11-21 02:20 UTC, iarna commented
Ok, I tracked down where this was added (https://github.com/npm/npm/issues/2959) and it's sufficiently well discussed and tested that I'm not comfortable taking this in a patch/minor release so I'm gonna reopen this and tag it to be in the next major release.

2017-11-21 02:21 UTC, iarna requested changes
I would also note that there are a couple of tests failing with this. Before we land this those will need to be updated to take it these changes into account.

2017-11-21 20:08 UTC, bburhans commented
The [official documentation](https://docs.npmjs.com/cli/test) says:
>[`npm test`] runs a package's "test" script, if one was provided.

That doesn't define any behavior if one was *not* provided, but I feel like it slightly implies *no* behavior in that case, because the "if one was provided" case is explicitly mentioned. If the expectation is that it break (e.g. stop a CI process) instead of do nothing, we should clarify that behavior or remove the "if none was provided" clause.

I don't know how many CI frameworks run `npm test` or `npm run test` out of the box, but if it's nonzero because of [the precedent we set in 2012](https://github.com/npm/npm/issues/2959), we might consider leaving it exiting zero. However, the modern npm init defaults are contrary:
```javascript
    "test": "echo \"Error: no test specified\" && exit 1"
```
We should make sure that the "no test script is (okay|bad)" expectation is consistent one way or the other.

Recommendation: use the word "error" and exit nonzero everywhere, or downgrade it to info/warn and exit zero everywhere. The discrepancy is misleading and sets a confusing precedent. `npm init` defaults, `npm test`, `npm run test`, and npm docs should all agree.

2018-07-10 23:02 UTC, zkat commented
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

2018-07-10 23:02 UTC, closed without merging