using env when has script-shell (Windows)
npm/npm pull request #19418
Opened 2017-12-18 09:27 UTC by gucong3000

Do not using default platform env: SET for run-script when has script-shell config.

2018-01-19 06:51 UTC, gucong3000 commented
Is there anything I can do to help this PR?

2018-03-11 22:34 UTC, andelmad approved these changes

2018-04-12 01:34 UTC, iarna commented
Hi @gucong3000, thank for your patience! While we don't officially support cygwin, I'm ok with taking patches for it that we can be confident won't cause other issues. In this case, I would suggest you add your Cygwin detection to `lib/utils/is-windows-bash.js` and then use that in the if statement here.

2018-04-12 01:37 UTC, iarna requested changes

2018-04-12 01:37 UTC, iarna commented on lib/run-script.js
> +        if (process.platform === 'win32' && !/^(msys|cygwin)$/.test(process.env.OSTYPE)) {
Use `/lib/utils/is-windows-bash.js` and update that to include cygwin.

2018-05-02 06:59 UTC, gucong3000 commented
@iarna Thanks for your patience. Modified.

2018-07-10 23:31 UTC, iarna commented on lib/utils/is-windows-bash.js
> +module.exports = isWindows && (env.MSYSTEM ? /^MINGW(32|64)$/.test(env.MSYSTEM) : env.TERM === "cygwin")
The env.MSYSTEM guard here is unnecessary.

2018-07-10 23:40 UTC, iarna commented
Thanks! This is landing as 4c32413a5b!

2018-07-10 23:40 UTC, closed without merging