Add excpetion to environment variable substitution for :_ and :__
npm/npm pull request #20177
Opened 2018-03-27 06:42 UTC by wilvk

Fixes https://github.com/npm/npm/issues/20159

Currently server-specific environment variables are being converted to hyphens with the regex replace, thus causing them to be inaccessible for things like credentials.

By running the command (in Linux):

```
env npm_config_//nexus:8081/nexus/content/repositories/npm-test/:_password=YWRtaW4xMjM= bash
```

An environment variable is present such as:

```
npm_config_//nexus:8081/nexus/content/repositories/npm-test/:_password=YWRtaW4xMjM=
```

this is interpreted as the config variable:

```
{ '//nexus:8081/nexus/content/repositories/npm-test/:-password': 'YWRtaW4xMjM=' }
```

Where the password component is incorrect (`-password` instead or `_password`). 
This prevents the password from being set correctly for use later on in `/lib/config/get-credentials-by-uri.js`.

The same applies for other environment variables such as `__auth`.

The replacement I've used is a bit 'clunky' so if anyone wants to clean it up a bit, feel free.

2018-04-03 04:39 UTC, wilvk commented
bump - any updates/feedback on this PR?

2018-04-09 19:17 UTC, iarna requested changes
Ok, so beyond the implementation nits, a change like this would need docs and tests too.

But beyond that I'm concerned that making this kind of change to processing will mess up someone else's weird edge case. As there is a work around for your use case that makes me inclined to play things safe here and not take this.

The work around, and in fact, how we encourage people to configure systems like this is:

Add the following to your `npmrc`:

```
 //nexus:8081/nexus/content/repositories/npm-test/:_password=${NEXUS_PASSWORD}
```

Then set the `NEXUS_PASSWORD` env var, eg

```
env NEXUS_PASWORD=YWRtaW4xMjM= bash
```

2018-04-09 19:17 UTC, iarna commented on lib/config/core.js
> +              .replace(/:__/, 'PLACEHOLDERTWO')
this second regexp will never match because `:__ABC` will be replaced with `PLACEHOLDERONE_ABC`

2018-04-09 19:17 UTC, iarna commented on lib/config/core.js
> +              .replace(/(?!^)_/g, '-')
I wonder if the placeholder business could be ditched in preference for:

`.replace(/(?!^)(⁈[_:])_/g, '-')`

That is, only change `_` to `-` if it's not preceded by the start of the string, a `:` or a `_` . It's not quite the same, granted…

2018-04-09 19:19 UTC, iarna commented
Oh, and if you'd like to chat more about this in real time I encourage you to drop by @js-npm on the https://package.community/ Discord.

2018-04-09 22:22 UTC, wilvk commented
Thanks for the reply @iarna , I wasn't aware that variable substitution worked in-line for `.npmrc`. The `$NEXUS_PASSWORD` approach seems like the best solution so will go with that for my stuff.

Will implement the docs, tests and suggested changes for if/when it is decided to go ahead with this PR.

Cheers,

2018-07-10 22:44 UTC, zkat commented
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

2018-07-10 22:44 UTC, closed without merging