Load dependencies into ideal tree if installing with arguments
npm/npm pull request #20198
Opened 2018-03-29 17:11 UTC by greysteil

Previously, dependencies were only loaded into the tree during install if no
arguments were passed. That caused git dependencies to be deleted from the
`package-lock.json`.

Fixes #16839 (again)

2018-03-29 17:15 UTC, greysteil commented
I've added all of my context for this PR [here](https://github.com/npm/npm/issues/16839#issuecomment-377306641). I'm not a JavaScript developer, but am pretty sure that this is the right fix. I'd love help from a maintainer to write a test for this and get it reviewed. :octocat:

2018-04-09 19:27 UTC, iarna requested changes
This is currently causing a LOT of test failures, there are reasons for the current behavior, vis-a-vis which modules are loaded when.

That being said, git modules being removed when they shouldn't be is something that should be resolved in the most recent releases (try `npm@next`). If it _isn't_ and you have a repro, I'd be happy to dig back into that. 

I'd be happy to chat more if you want to join the https://package.community/ Discord and drop by the #js-npm channel.

2018-04-14 21:19 UTC, greysteil commented
Thanks @iarna. The reproduction steps in https://github.com/npm/npm/issues/16839#issuecomment-377306641 still reproduce the bug on `5.9.0-next.0`. I'll have another dig into this now, but would love your help.

2018-04-14 22:15 UTC, greysteil commented
Dsicussed with @iarna on #js-npm channel and she has a much better fix than I could ever come up with. I'll leave this open so she can close it when she pushes it.

Thanks @iarna! ❤️

2018-04-18 17:49 UTC, ezze commented
@iarna, @greysteil, what is a fix? When will it be released? This is a blocking bug for our npm usage since 5.0.0.

2018-04-18 19:58 UTC, greysteil commented
@iarna's fix is to add the following to `doesChildVersionMatch`:

```
  if (requested.type === 'git' && child.fromShrinkwrap) {
    const fromSw = child.fromShrinkwrap
    // FIXME: if we start storing the install specifier for git repos in the lockfile

    // might not be true, but we can't tell currently
    if (!fromSw.hosted && !requested.hosted) return true

    return fromSw.hosted.toString() === requested.hosted.toString()
  }
```

Should drop in npm 6, which will be released this week.

2018-05-04 01:20 UTC, iarna commented
It is indeed out in npm@6.0.0, try it out today! =)

2018-05-04 01:20 UTC, closed without merging