Add support for `npm init <create-pkg-name>`.
npm/npm pull request #20303
Opened 2018-04-11 06:39 UTC by jdalton

_(Just starting the PR to add `npm init <create-pkg-name>` support.
I'll fill this in over the next couple days.

2018-04-11 23:27 UTC, jdalton commented on lib/init.js
> +
The promise returned by `npx` is a vanilla promise (not a bluebird one) so lacks the `nodeify` helper.
The promise `then(cb)` is executed before the `npm init` command finishes (possibly before it starts).

2018-04-11 23:28 UTC, jdalton commented on lib/init.js
> +
☝️ That regexp is the key yarn/npm interoperable bit.

2018-04-12 05:33 UTC, jdalton commented on lib/init.js
> +
The promise `then(cb)` is executed before the `npm init` command finishes which causes the process to exit.
There is a PR open on `npx` to return a promise to execute the `cb` after `npx` runs its command.
https://github.com/zkat/npx/pull/172

2018-04-12 05:37 UTC, jdalton commented
Any guidance on unit tests would be appreciated.

2018-04-12 16:07 UTC, jdalton commented on lib/init.js
> +
👆 In addition to following yarn's rules, name expansion also supports transforming `@scope` into `@scope/create`.

2018-04-12 16:38 UTC, zkat commented
@jdalton as far as unit tests go, I would mock `bin/npx-cli.js` and just make sure it's being called with the right arguments.

2018-04-12 16:51 UTC, jdalton commented
@zkat
> as far as unit tests go, I would mock bin/npx-cli.js and just make sure it's being called with the right arguments.

Cool!

2018-04-12 16:51 UTC, jdalton commented
Note: This PR [depends](https://github.com/npm/npm/pull/20303#discussion_r180927254) on https://github.com/zkat/npx/pull/172 _(however it is resolved)_.

2018-04-18 02:01 UTC, jdalton commented
Added tests!

2018-04-18 18:47 UTC, zkat requested changes

2018-04-18 18:47 UTC, zkat commented on lib/init.js
>  init.usage = 'npm init [--force|-f|--yes|-y]'
This should be updated. You should document this feature in `doc/cli/npm-init.md` as well.

2018-04-18 18:47 UTC, zkat commented on package.json
> +    "libnpx": "^10.2.0",
This can be removed -- I've updated libnpx

2018-04-18 20:27 UTC, jdalton commented
Added docs and removed the `libnpx` bump in the package.json.

2018-04-18 20:48 UTC, zkat approved these changes

2018-04-18 21:01 UTC, merged

2018-04-18 21:08 UTC, jdalton commented
Thank you 🎉

2018-04-19 19:27 UTC, statianzo commented on lib/config/cmd-list.js
> +  'create': 'init',
Thanks for this alias 👍

2018-04-19 21:30 UTC, jdalton commented on lib/config/cmd-list.js
> +  'create': 'init',
Thanks goes to @zkat :clap: