view: stop crashing when license field is an object
npm/npm pull request #20538
Opened 2018-05-07 20:06 UTC by zkat

2018-05-07 20:08 UTC, joeledwards commented on lib/view.js
> +        : (licenseField.type || 'Proprierary'),
`Proprierary` should be `Proprietary`

2018-05-07 20:08 UTC, joeledwards requested changes

2018-05-07 20:08 UTC, joeledwards commented on lib/view.js
> +    const licenseField = manifest.license || manifest.licence || 'Proprierary'
🍎

2018-05-08 00:24 UTC, zkat commented
@joeledwards wanna re-review?

2018-05-08 01:08 UTC, joeledwards approved these changes
Looks good. Thanks!

2018-05-11 21:43 UTC, merged