ci: pause log before logging summary
npm/npm pull request #20715
Opened 2018-05-22 16:29 UTC by legodude17

From [here](https://npm.trydiscourse.com/t/npm-ci-progress-bar-not-properly-removed/61/2), this will remove the progress bar before logging the summary, so that it doesn't log the summary over the progress bar and print something like `added 2 pacakges in 0.966sractTree: extractTree`.

2018-05-22 18:58 UTC, zkat requested changes

2018-05-22 18:58 UTC, zkat commented on lib/ci.js
> +        npmlog.pause()
This should be `.disableProgress()`

2018-05-22 19:50 UTC, legodude17 commented on lib/ci.js
> +        npmlog.pause()
Ah thanks.

2018-05-23 01:13 UTC, zkat approved these changes
Looks good!

2018-05-23 01:13 UTC, legodude17 commented
@zkat Fixed!

2018-05-23 01:45 UTC, legodude17 commented
@zkat Great!

2018-05-23 04:28 UTC, merged

2018-05-23 14:20 UTC, legodude17 commented
🎉